language: node_js
node_js:
  - node
cache:
  directories:
    - "node_modules"
before_scripts:
  - touch config.debug.yaml
  - touch config.production.yaml
script:
  - npm run build:server
  - npm run build:ui

